config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), 
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'#url 네임 스페이스로 다른 앱이 추가되어 별칭이 같아도 사용할 수 있게

urlpatterns = [
    path('', views.index, name='index'),#8000/pybo 뒤에 index 밑에는 /pybo2와 같은 detail부여 이걸로 템플릿에서 사용가능
    path('<int:question_id>/', views.detail, name='detail'),
    #
    path('answer/create/<int:question_id>/',views.answer_create, name='answer_create'),
    #페이지를 호출하면 views.answer_create로 인해 함수가 호출됨 
]

pybo/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)
    # 제목
    content = models.TextField() #내용
    create_date = models.DateTimeField() #작성일지

    def __str__(self) -> str:
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    #foreignkey는 질문에 대한 답으로 question하고 연결하는데 사용됨 on_delete=models.CASCADE는 질문이 삭제될경우 답변도 삭제 cascade는 질문에 대한 모든 답변을 삭제한다는 의미도 있음
    content = models.TextField()
    create_date = models.DateTimeField()



class Review(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)

pybo/views.py
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import Http404
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from .models import Question

def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
   
   # question = Question.objects.get(id=question_id)
   question = get_object_or_404(Question, pk=question_id)#pk는 question 모델의 기본키 primary key에 해당함
   context = {'question': question}
   return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('pybo:detail', question_id=question.id)


# Create your views here.

templates/pybo/question_detail.html
<h1>{{ question.subject }}</h1>
<div>{{ question.content }}</div>
<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<!--질문에 등록된 답변 확인 count는 답변의 총 갯수를 의미함 -->
<div>
  <ul>
    {% for answer in question.answer_set.all %}
    <li>{{ answer.content }}</li>
    {% endfor %}<!--for문 마무리 할려면 무조건 넣어야함 -->
  </ul>
</div>
<form action="{% url 'pybo:answer_create' question.id %}" method="post">
  {% csrf_token %}
  <textarea name="content" id="content" rows="15"></textarea>
  <input type="submit" value="답변등록" />
</form>

templates/pybo/question_list.html
{% if question_list %}
<ul>
  {% for question in question_list %}
  <li>
    <a href="{%url 'pybo:detail' question.id %}">{{ question.subject }}</a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>질문이 없습니다.</p>
{% endif %}